In [2]:
import pandas as pd
import numpy as np

In [3]:
province_id = pd.read_excel('../../diabeteschronicabuserprojectihio/Test_sample/Test/province_id.xlsx')
province_id.set_index('province_id_iso', inplace=True)
province_id = province_id['province_name_en']
province_id

province_id_iso
0                        Markazi
1                          Gilan
2                     Mazandaran
3               Azerbaijan, East
4               Azerbaijan, West
5                     Kermanshah
6                      Khuzestan
7                           Fars
8                         Kerman
9               Khorasan, Razavi
10                       Isfahan
11        Sistan and Baluchestan
12                     Kurdistan
13                       Hamadan
14     Chaharmahal and Bakhtiari
15                      Lorestan
16                          Ilam
17    Kohgiluyeh and Boyer-Ahmad
18                       Bushehr
19                        Zanjan
20                        Semnan
21                          Yazd
22                     Hormozgan
23                        Tehran
24                       Ardabil
25                           Qom
26                        Qazvin
27                      Golestan
28               Khorasan, North
29               Khorasan, South
30                        Alborz
Name: province_name_en, dtype: object

In [4]:
# table = pd.read_csv('../person_table.csv', index_col=[0, 1])
table = pd.read_clipboard()
table

                                                    0                    1  \
age_cat  [18, 39]                 25.34 (25.19-25.49)  26.32 (26.17-26.46)
         [40, 64]                 50.49 (50.32-50.67)   49.84 (49.68-50.0)
         [65, 95]                 24.17 (24.01-24.32)   23.84 (23.7-23.98)
gender   1                        37.99 (37.82-38.16)  34.23 (34.07-34.38)
         0                        62.01 (61.84-62.18)  65.77 (65.62-65.93)
fund     Civil servants           26.12 (25.97-26.28)  37.11 (36.95-37.27)
         Rural                    39.35 (39.18-39.52)   23.6 (23.46-23.74)
         Iranian + Self-employed  11.45 (11.34-11.57)  14.16 (14.05-14.28)
         Universal                16.95 (16.82-17.08)   17.07 (16.95-17.2)
         Others                      5.75 (5.67-5.83)     7.85 (7.77-7.94)
         Foreign                      0.37 (0.35-0.4)     0.21 (0.19-0.22)
province 1                            5.6 (5.52-5.68)     5.33 (5.26-5.41)
         0                           2.12 (2.07-2.17)     2.07 (2.02-2.11)
         23                       19.81 (19.67-19.95)  19.46 (19.33-19.59)
         7                           9.49 (9.38-9.59)  11.13 (11.03-11.23)
         9                        12.43 (12.31-12.54)  11.33 (11.23-11.43)
         10                          8.55 (8.45-8.65)    9.95 (9.85-10.05)
         2                            6.91 (6.82-7.0)      5.87 (5.8-5.95)
         11                          2.89 (2.83-2.95)     3.41 (3.35-3.47)
         27                          3.41 (3.35-3.48)     3.18 (3.12-3.24)
         8                           4.31 (4.24-4.38)      4.14 (4.07-4.2)
         5                           2.76 (2.71-2.82)     2.77 (2.71-2.82)
         12                          2.58 (2.53-2.64)     2.82 (2.77-2.88)
         13                          3.05 (2.99-3.11)     2.71 (2.65-2.76)
         15                          2.38 (2.33-2.44)     2.48 (2.43-2.54)
         21                           2.45 (2.4-2.51)      2.5 (2.45-2.55)
         16                          0.69 (0.66-0.71)     0.74 (0.72-0.77)
         22                          2.27 (2.21-2.32)      1.66 (1.61-1.7)
         14                          1.38 (1.34-1.42)     1.39 (1.35-1.43)
         18                          1.41 (1.37-1.45)     1.39 (1.35-1.43)
         17                          0.84 (0.81-0.87)      0.9 (0.86-0.93)
         28                          1.07 (1.03-1.11)      1.2 (1.16-1.24)
         26                          1.19 (1.15-1.23)      1.24 (1.2-1.27)
         19                           1.34 (1.3-1.38)      1.2 (1.16-1.23)
         29                          1.07 (1.04-1.11)      1.14 (1.1-1.17)
total    number                                311685               359121

                                                    2                    3  \
age_cat  [18, 39]                  26.24 (26.1-26.39)  26.81 (26.65-26.96)
         [40, 64]                  50.96 (50.8-51.12)   52.03 (51.86-52.2)
         [65, 95]                  22.8 (22.66-22.94)  21.17 (21.03-21.31)
gender   1                         32.06 (31.9-32.21)  30.18 (30.02-30.34)
         0                         67.94 (67.79-68.1)  69.82 (69.66-69.98)
fund     Civil servants           44.42 (44.26-44.58)   49.5 (49.33-49.67)
         Rural                    16.37 (16.24-16.49)   11.4 (11.29-11.51)
         Iranian + Self-employed  14.73 (14.61-14.84)  14.86 (14.74-14.98)
         Universal                 14.51 (14.4-14.63)  11.38 (11.27-11.49)
         Others                      9.89 (9.79-9.99)  12.83 (12.71-12.94)
         Foreign                      0.09 (0.08-0.1)     0.03 (0.02-0.04)
province 1                           5.39 (5.32-5.47)     5.29 (5.21-5.37)
         0                           2.01 (1.96-2.05)     2.02 (1.97-2.07)
         23                       18.65 (18.52-18.78)  16.55 (16.42-16.67)
         7                        11.74 (11.63-11.84)   11.91 (11.8-12.02)
         9                        10.64 (10.54-10.75)    10.5 (10.4-10.61)
         10                       10.42 (10.32-10.52)    10.7 (10.6-10.81)
         2                           5.69 (5.61-5.76)     5.43 (5.36-5.51)
         11                          3.78 (3.72-3.85)     4.54 (4.47-4.61)
         27                          3.28 (3.22-3.34)     3.58 (3.51-3.64)
         8                            3.84 (3.77-3.9)      3.54 (3.48-3.6)
         5                           3.18 (3.12-3.23)      3.7 (3.64-3.76)
         12                          3.06 (3.01-3.12)     3.13 (3.07-3.19)
         13                          2.72 (2.67-2.77)     2.68 (2.62-2.73)
         15                          2.37 (2.32-2.42)     2.57 (2.52-2.62)
         21                          2.51 (2.46-2.56)      2.4 (2.35-2.45)
         16                           0.97 (0.94-1.0)     1.45 (1.41-1.49)
         22                           1.4 (1.36-1.44)     1.27 (1.23-1.31)
         14                          1.29 (1.26-1.33)     1.39 (1.35-1.43)
         18                          1.41 (1.37-1.45)     1.42 (1.38-1.46)
         17                           1.03 (1.0-1.06)     1.35 (1.32-1.39)
         28                           1.2 (1.16-1.23)      1.26 (1.22-1.3)
         26                          1.18 (1.15-1.22)     1.11 (1.07-1.14)
         19                           1.14 (1.1-1.17)     1.04 (1.01-1.08)
         29                           1.1 (1.07-1.13)      1.14 (1.1-1.18)
total    number                                358920               332538

                                                    4                  all
age_cat  [18, 39]                 25.34 (25.19-25.48)  26.02 (25.96-26.09)
         [40, 64]                 55.82 (55.65-55.98)   51.82 (51.75-51.9)
         [65, 95]                 18.85 (18.72-18.98)   22.16 (22.1-22.22)
gender   1                        31.18 (31.02-31.33)  33.06 (32.99-33.13)
         0                        68.82 (68.67-68.98)  66.94 (66.87-67.01)
fund     Civil servants            50.93 (50.76-51.1)   41.83 (41.76-41.9)
         Rural                        6.48 (6.4-6.56)   19.14 (19.08-19.2)
         Iranian + Self-employed   12.31 (12.2-12.42)    13.55 (13.5-13.6)
         Universal                   6.17 (6.08-6.25)  13.21 (13.16-13.26)
         Others                   24.11 (23.96-24.25)  12.13 (12.08-12.18)
         Foreign                       0.0 (0.0-0.01)     0.14 (0.13-0.14)
province 1                           5.93 (5.86-6.01)     5.51 (5.47-5.54)
         0                           2.04 (1.99-2.09)     2.05 (2.03-2.07)
         23                       11.76 (11.66-11.87)   17.24 (17.18-17.3)
         7                          11.1 (10.99-11.2)   11.1 (11.06-11.15)
         9                         10.09 (9.99-10.19)  10.98 (10.93-11.02)
         10                         9.91 (9.81-10.01)     9.93 (9.89-9.98)
         2                           5.28 (5.21-5.36)     5.82 (5.78-5.85)
         11                          5.19 (5.12-5.26)      3.97 (3.94-4.0)
         27                           5.38 (5.3-5.45)     3.76 (3.73-3.79)
         8                            2.7 (2.65-2.76)      3.7 (3.67-3.73)
         5                           5.16 (5.08-5.23)     3.51 (3.49-3.54)
         12                          2.68 (2.62-2.73)     2.86 (2.84-2.89)
         13                          2.87 (2.81-2.92)      2.8 (2.77-2.82)
         15                           3.24 (3.18-3.3)     2.61 (2.59-2.64)
         21                           1.8 (1.75-1.84)     2.33 (2.31-2.36)
         16                          3.67 (3.61-3.73)     1.51 (1.49-1.53)
         22                          0.98 (0.95-1.02)      1.5 (1.49-1.52)
         14                           1.7 (1.65-1.74)     1.43 (1.41-1.45)
         18                          1.31 (1.27-1.35)     1.39 (1.37-1.41)
         17                          2.66 (2.61-2.71)     1.36 (1.34-1.37)
         28                           1.66 (1.61-1.7)      1.28 (1.26-1.3)
         26                          0.91 (0.88-0.94)     1.13 (1.11-1.14)
         19                           0.9 (0.87-0.93)     1.12 (1.11-1.14)
         29                          1.08 (1.04-1.11)     1.11 (1.09-1.12)
total    number                                341918              1704182

In [5]:
table.rename({'all': 'All'}, axis=1, inplace=True)

In [6]:
temp = table.loc['province'].index.astype(float)

In [7]:
prov_index = pd.MultiIndex.from_product([['province'], province_id.loc[temp].values])

In [8]:
prov_index

MultiIndex([('province',                      'Gilan'),
            ('province',                    'Markazi'),
            ('province',                     'Tehran'),
            ('province',                       'Fars'),
            ('province',           'Khorasan, Razavi'),
            ('province',                    'Isfahan'),
            ('province',                 'Mazandaran'),
            ('province',     'Sistan and Baluchestan'),
            ('province',                   'Golestan'),
            ('province',                     'Kerman'),
            ('province',                 'Kermanshah'),
            ('province',                  'Kurdistan'),
            ('province',                    'Hamadan'),
            ('province',                   'Lorestan'),
            ('province',                       'Yazd'),
            ('province',                       'Ilam'),
            ('province',                  'Hormozgan'),
            ('province',  'Chaharmahal and Bakhtiari'),
            ('province',                    'Bushehr'),
            ('province', 'Kohgiluyeh and Boyer-Ahmad'),
            ('province',            'Khorasan, North'),
            ('province',                     'Qazvin'),
            ('province',                     'Zanjan'),
            ('province',            'Khorasan, South')],
           )

In [9]:
prov = pd.DataFrame(index=prov_index, data=table.loc['province'].values, columns=table.columns)

In [10]:
table = pd.concat(
    [table.drop('province', axis=0, level=0), prov]
)

In [11]:
table

                                                       0                    1  \
age_cat  [18, 39]                    25.34 (25.19-25.49)  26.32 (26.17-26.46)
         [40, 64]                    50.49 (50.32-50.67)   49.84 (49.68-50.0)
         [65, 95]                    24.17 (24.01-24.32)   23.84 (23.7-23.98)
gender   1                           37.99 (37.82-38.16)  34.23 (34.07-34.38)
         0                           62.01 (61.84-62.18)  65.77 (65.62-65.93)
fund     Civil servants              26.12 (25.97-26.28)  37.11 (36.95-37.27)
         Rural                       39.35 (39.18-39.52)   23.6 (23.46-23.74)
         Iranian + Self-employed     11.45 (11.34-11.57)  14.16 (14.05-14.28)
         Universal                   16.95 (16.82-17.08)   17.07 (16.95-17.2)
         Others                         5.75 (5.67-5.83)     7.85 (7.77-7.94)
         Foreign                         0.37 (0.35-0.4)     0.21 (0.19-0.22)
total    number                                   311685               359121
province Gilan                           5.6 (5.52-5.68)     5.33 (5.26-5.41)
         Markazi                        2.12 (2.07-2.17)     2.07 (2.02-2.11)
         Tehran                      19.81 (19.67-19.95)  19.46 (19.33-19.59)
         Fars                           9.49 (9.38-9.59)  11.13 (11.03-11.23)
         Khorasan, Razavi            12.43 (12.31-12.54)  11.33 (11.23-11.43)
         Isfahan                        8.55 (8.45-8.65)    9.95 (9.85-10.05)
         Mazandaran                      6.91 (6.82-7.0)      5.87 (5.8-5.95)
         Sistan and Baluchestan         2.89 (2.83-2.95)     3.41 (3.35-3.47)
         Golestan                       3.41 (3.35-3.48)     3.18 (3.12-3.24)
         Kerman                         4.31 (4.24-4.38)      4.14 (4.07-4.2)
         Kermanshah                     2.76 (2.71-2.82)     2.77 (2.71-2.82)
         Kurdistan                      2.58 (2.53-2.64)     2.82 (2.77-2.88)
         Hamadan                        3.05 (2.99-3.11)     2.71 (2.65-2.76)
         Lorestan                       2.38 (2.33-2.44)     2.48 (2.43-2.54)
         Yazd                            2.45 (2.4-2.51)      2.5 (2.45-2.55)
         Ilam                           0.69 (0.66-0.71)     0.74 (0.72-0.77)
         Hormozgan                      2.27 (2.21-2.32)      1.66 (1.61-1.7)
         Chaharmahal and Bakhtiari      1.38 (1.34-1.42)     1.39 (1.35-1.43)
         Bushehr                        1.41 (1.37-1.45)     1.39 (1.35-1.43)
         Kohgiluyeh and Boyer-Ahmad     0.84 (0.81-0.87)      0.9 (0.86-0.93)
         Khorasan, North                1.07 (1.03-1.11)      1.2 (1.16-1.24)
         Qazvin                         1.19 (1.15-1.23)      1.24 (1.2-1.27)
         Zanjan                          1.34 (1.3-1.38)      1.2 (1.16-1.23)
         Khorasan, South                1.07 (1.04-1.11)      1.14 (1.1-1.17)

                                                       2                    3  \
age_cat  [18, 39]                     26.24 (26.1-26.39)  26.81 (26.65-26.96)
         [40, 64]                     50.96 (50.8-51.12)   52.03 (51.86-52.2)
         [65, 95]                     22.8 (22.66-22.94)  21.17 (21.03-21.31)
gender   1                            32.06 (31.9-32.21)  30.18 (30.02-30.34)
         0                            67.94 (67.79-68.1)  69.82 (69.66-69.98)
fund     Civil servants              44.42 (44.26-44.58)   49.5 (49.33-49.67)
         Rural                       16.37 (16.24-16.49)   11.4 (11.29-11.51)
         Iranian + Self-employed     14.73 (14.61-14.84)  14.86 (14.74-14.98)
         Universal                    14.51 (14.4-14.63)  11.38 (11.27-11.49)
         Others                         9.89 (9.79-9.99)  12.83 (12.71-12.94)
         Foreign                         0.09 (0.08-0.1)     0.03 (0.02-0.04)
total    number                                   358920               332538
province Gilan                          5.39 (5.32-5.47)     5.29 (5.21-5.37)
         Markazi                        2.01 (1.96-2.05)     2.02 (1.97-2.07)
         Tehran                      18.65 (18.52-18.78)  16.55 (16.42-16.67)
         Fars                        11.74 (11.63-11.84)   11.91 (11.8-12.02)
         Khorasan, Razavi            10.64 (10.54-10.75)    10.5 (10.4-10.61)
         Isfahan                     10.42 (10.32-10.52)    10.7 (10.6-10.81)
         Mazandaran                     5.69 (5.61-5.76)     5.43 (5.36-5.51)
         Sistan and Baluchestan         3.78 (3.72-3.85)     4.54 (4.47-4.61)
         Golestan                       3.28 (3.22-3.34)     3.58 (3.51-3.64)
         Kerman                          3.84 (3.77-3.9)      3.54 (3.48-3.6)
         Kermanshah                     3.18 (3.12-3.23)      3.7 (3.64-3.76)
         Kurdistan                      3.06 (3.01-3.12)     3.13 (3.07-3.19)
         Hamadan                        2.72 (2.67-2.77)     2.68 (2.62-2.73)
         Lorestan                       2.37 (2.32-2.42)     2.57 (2.52-2.62)
         Yazd                           2.51 (2.46-2.56)      2.4 (2.35-2.45)
         Ilam                            0.97 (0.94-1.0)     1.45 (1.41-1.49)
         Hormozgan                       1.4 (1.36-1.44)     1.27 (1.23-1.31)
         Chaharmahal and Bakhtiari      1.29 (1.26-1.33)     1.39 (1.35-1.43)
         Bushehr                        1.41 (1.37-1.45)     1.42 (1.38-1.46)
         Kohgiluyeh and Boyer-Ahmad      1.03 (1.0-1.06)     1.35 (1.32-1.39)
         Khorasan, North                 1.2 (1.16-1.23)      1.26 (1.22-1.3)
         Qazvin                         1.18 (1.15-1.22)     1.11 (1.07-1.14)
         Zanjan                          1.14 (1.1-1.17)     1.04 (1.01-1.08)
         Khorasan, South                 1.1 (1.07-1.13)      1.14 (1.1-1.18)

                                                       4                  All
age_cat  [18, 39]                    25.34 (25.19-25.48)  26.02 (25.96-26.09)
         [40, 64]                    55.82 (55.65-55.98)   51.82 (51.75-51.9)
         [65, 95]                    18.85 (18.72-18.98)   22.16 (22.1-22.22)
gender   1                           31.18 (31.02-31.33)  33.06 (32.99-33.13)
         0                           68.82 (68.67-68.98)  66.94 (66.87-67.01)
fund     Civil servants               50.93 (50.76-51.1)   41.83 (41.76-41.9)
         Rural                           6.48 (6.4-6.56)   19.14 (19.08-19.2)
         Iranian + Self-employed      12.31 (12.2-12.42)    13.55 (13.5-13.6)
         Universal                      6.17 (6.08-6.25)  13.21 (13.16-13.26)
         Others                      24.11 (23.96-24.25)  12.13 (12.08-12.18)
         Foreign                          0.0 (0.0-0.01)     0.14 (0.13-0.14)
total    number                                   341918              1704182
province Gilan                          5.93 (5.86-6.01)     5.51 (5.47-5.54)
         Markazi                        2.04 (1.99-2.09)     2.05 (2.03-2.07)
         Tehran                      11.76 (11.66-11.87)   17.24 (17.18-17.3)
         Fars                          11.1 (10.99-11.2)   11.1 (11.06-11.15)
         Khorasan, Razavi             10.09 (9.99-10.19)  10.98 (10.93-11.02)
         Isfahan                       9.91 (9.81-10.01)     9.93 (9.89-9.98)
         Mazandaran                     5.28 (5.21-5.36)     5.82 (5.78-5.85)
         Sistan and Baluchestan         5.19 (5.12-5.26)      3.97 (3.94-4.0)
         Golestan                        5.38 (5.3-5.45)     3.76 (3.73-3.79)
         Kerman                          2.7 (2.65-2.76)      3.7 (3.67-3.73)
         Kermanshah                     5.16 (5.08-5.23)     3.51 (3.49-3.54)
         Kurdistan                      2.68 (2.62-2.73)     2.86 (2.84-2.89)
         Hamadan                        2.87 (2.81-2.92)      2.8 (2.77-2.82)
         Lorestan                        3.24 (3.18-3.3)     2.61 (2.59-2.64)
         Yazd                            1.8 (1.75-1.84)     2.33 (2.31-2.36)
         Ilam                           3.67 (3.61-3.73)     1.51 (1.49-1.53)
         Hormozgan                      0.98 (0.95-1.02)      1.5 (1.49-1.52)
         Chaharmahal and Bakhtiari       1.7 (1.65-1.74)     1.43 (1.41-1.45)
         Bushehr                        1.31 (1.27-1.35)     1.39 (1.37-1.41)
         Kohgiluyeh and Boyer-Ahmad     2.66 (2.61-2.71)     1.36 (1.34-1.37)
         Khorasan, North                 1.66 (1.61-1.7)      1.28 (1.26-1.3)
         Qazvin                         0.91 (0.88-0.94)     1.13 (1.11-1.14)
         Zanjan                          0.9 (0.87-0.93)     1.12 (1.11-1.14)
         Khorasan, South                1.08 (1.04-1.11)     1.11 (1.09-1.12)

In [13]:
# Saving person_table.xlsx
# table.to_excel('../person_table_edited.xlsx')
# table.to_excel('../Edited fund/person_table_f.xlsx')